### ISSUE TITLE
Problème de compilation du frontend lors de l'utilisation de Docker Compose

### ISSUE THREAD

**Issue by Namo2202** [Namo2202/ci-cd-h3#1]
Lorsque j'essaie de démarrer mes services frontend et backend à l'aide de Docker Compose, je rencontre un problème de compilation du frontend. Plus précisément, le backend se compile avec succès, mais le frontend échoue avec l'erreur suivante :
![Screenshot from 2024-02-01 11-18-04](https://github.com/Namo2202/ci-cd-h3/assets/73890085/8ddbe8e5-3770-468b-9091-332c07b6a6ca)

**Comment by bdallard** [comment]
hello, essaie de build juste l'image docker du front avant de lancer le docker-compose direct. 
J'ai vu que tu faisais `npm start` essaie de `npm build` ton app et de la lancer en mode production comme ca : https://create-react-app.dev/docs/deployment/

**Comment by Namo2202** [comment]
Re Benjamin, j'ai testé ta solution et la compilation a fonctionnée. Merci !

**Comment by Namo2202** [comment]
Re Benjamin, j'ai testé ta solution et la compilation a fonctionnée. Merci !
